// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlaceParser.Data;

namespace PlaceParser.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190317201537_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlaceParser.Models.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<Guid>("GoogleId");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<Guid>("PlaceId");

                    b.Property<Guid>("PlaceType");

                    b.Property<string>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("PlaceParser.Models.PlaceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PlaceTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
